server {
    listen 80;
    
    # Local dos arquivos do site (gerados pelo build)
    root /usr/share/nginx/html;
    index index.html;

    # Configuração SPA (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    #  Proxy Reverso
    location /api {
        # 'backend' será o nome do container no Docker Compose
        proxy_pass http://api-cachorros:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}