from datetime import date
from sqlmodel import SQLModel, Field
from sqlalchemy import Date

class Cachorro(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    nome: str = Field(index=True, max_length=100)
    raca: str = Field(max_length=50)
    data_nascimento: date | None = Field(default=None, sa_type=Date)
    porte: str = Field(max_length=20)
    nome_tutor: str | None = Field(default=None, max_length=100)
    contato: str | None = Field(default=None, max_length=11)
    contato_2: str | None = Field(default=None, max_length=11)
    endereco_tutor: str | None = Field(default=None, max_length=255)
    castrado: bool | None = Field(default=None)
    vacina_antirrabica: date | None = Field(default=None, sa_type=Date)
    vacina_polivalente: date | None = Field(default=None, sa_type=Date)
    passeia: bool | None = Field(default=None)
    necessidades_em_casa: bool | None = Field(default=None)
    plano_de_saude: bool | None = Field(default=None)
    nome_plano_de_saude: str | None = Field(default=None, max_length=100)
    contato_veterinario: str | None = Field(default=None, max_length=11)
    endereco_clinica_veterinaria: str | None = Field(default=None, max_length=255)
    contato_clinica_veterinaria_24_horas: str | None = Field(default=None, max_length=11)
    endereco_clinica_veterinaria_24_horas: str | None = Field(default=None, max_length=255)
    restricao_alimentar: bool | None = Field(default=None)
    descricao_restricao_alimentar: str | None = Field(default=None, max_length=255)
    horario_alimentacao_manha: str | None = Field(default=None, max_length=50)
    porcao_alimentacao_manha: str | None = Field(default=None, max_length=100)
    horario_alimentacao_tarde: str | None = Field(default=None, max_length=50)
    porcao_alimentacao_tarde: str | None = Field(default=None, max_length=100)
    horario_alimentacao_noite: str | None = Field(default=None, max_length=50)
    porcao_alimentacao_noite: str | None = Field(default=None, max_length=100)
    restricao_medica: bool | None = Field(default=None)
    descricao_restricao_medica: str | None= Field(default=None, max_length=255)
    utiliza_medicacao: bool | None = Field(default=None)
    descricao_utiliza_medicacao: str | None = Field(default=None, max_length=500)
    comportamento: str | None = Field(default=None, max_length=1000)
    medo: str | None = Field(default=None, max_length=1000)
    relacionamento_com_outros_animais: str | None = Field(default=None, max_length=1000)
    relacionamento_com_pessoas: str | None = Field(default=None, max_length=1000)
    dependente: bool | None = Field(default=None)
    experiencia_com_hospedagem: bool | None = Field(default=None)
    descricao_experiencia_com_hospedagem: str | None = Field(default=None, max_length=255)
    posse_alimento: bool | None = Field(default=None)
    posse_objeto: bool | None = Field(default=None)
    descricao_posse_objeto: str | None = Field(default=None, max_length=255)