from datetime import date
from sqlmodel import Session, delete
from app.db import engine
from app.models import Cachorro

def seed_database():
    with Session(engine) as session:
        session.exec(delete(Cachorro))
        session.commit()

        cachorros_demo = [
            Cachorro(
                nome="Thor",
                raca="Golden Retriever",
                data_nascimento=date(2020, 5, 10),
                porte="Grande",
                nome_tutor="João Mendes",
                contato="41993399999",
                contato_2="41888855588",
                endereco_tutor="Avenida 7 de setembro, 123",
                castrado=True,
                vacina_antirrabica=date(2025, 11, 5),
                vacina_polivalente=date(2026, 1, 5),
                necessidades_em_casa=False,
                plano_de_saude=True,
                nome_plano_de_saude="Petlove",
                passeia=True,
                contato_veterinario="41777777777",
                endereco_clinica_veterinaria="Rua das flores, 123",
                contato_clinica_veterinaria_24_horas="4124242424",
                endereco_clinica_veterinaria_24_horas="Avenida iguaçu, 123",
                restricao_alimentar=True,
                descricao_restricao_alimentar="Intolerância a carne de frango",
                horario_alimentacao_manha="08h",
                porcao_alimentacao_manha="120g",
                horario_alimentacao_noite="19h",
                porcao_alimentacao_noite="120g",
                restricao_medica=False,
                utiliza_medicacao=False,
                comportamento="Brincalhão e dócil",
                medo="Medo de fogos de artifícil e escapamento de automóveis",
                relacionamento_com_outros_animais="Adora outros cachorros. Durante o passeio quer se comunicar com todos os cachorros que vê.",
                relacionamento_com_pessoas="Muito tranquilo com novas pessoas.",
                dependente=False,
                experiencia_com_hospedagem=True,
                descricao_experiencia_com_hospedagem="Frequenta creche 3 vezes por semana e já se hospedou algumas vezes em doghero.",
                posse_alimento=False,
                posse_objeto=False,
            ),

            Cachorro(
                nome="Mel",
                raca="SRD",
                data_nascimento=date(2019, 8, 15),
                porte="Médio",
                nome_tutor="Ana Souza",
                contato="41988887777",
                contato_2="41123456789",
                endereco_tutor="Rua XV de Novembro, 500",
                castrado=True,
                vacina_antirrabica=date(2025, 12, 1),
                vacina_polivalente=date(2026, 2, 10),
                necessidades_em_casa=True,
                plano_de_saude=False,
                passeia=True,
                contato_veterinario="4133334444",
                endereco_clinica_veterinaria="Av. Cândido de Abreu, 200",
                restricao_alimentar=False,
                horario_alimentacao_manha="07h30",
                porcao_alimentacao_manha="150g",
                horario_alimentacao_noite="18h30",
                porcao_alimentacao_noite="150g",
                restricao_medica=False,
                utiliza_medicacao=True,
                descricao_utiliza_medicacao="Vitamina para articulação (Condroplex) 1x ao dia pela manhã",
                comportamento="Muito agitada e carinhosa. Pula nas pessoas para cumprimentar.",
                medo="Trovões e barulhos muito altos.",
                relacionamento_com_outros_animais="Se dá bem com todos, mas pode ser invasiva brincando.",
                relacionamento_com_pessoas="Ama todas as pessoas.",
                dependente=True,
                experiencia_com_hospedagem=False,
                posse_alimento=True,
                posse_objeto=False,
            ),

            Cachorro(
                nome="Paçoca",
                raca="Chihuahua",
                data_nascimento=date(2022, 3, 20),
                porte="Pequeno",
                nome_tutor="Mariana Lima",
                contato="41977776666",
                contato_2="41888881111",
                endereco_tutor="Rua Mateus Leme, 800",
                castrado=False,
                vacina_antirrabica=date(2025, 10, 10),
                vacina_polivalente=date(2025, 11, 10),
                necessidades_em_casa=False,
                plano_de_saude=True,
                nome_plano_de_saude="Nofaro",
                passeia=True,
                contato_veterinario="41999991111",
                endereco_clinica_veterinaria="Rua Padre Anchieta, 100",
                restricao_alimentar=True,
                descricao_restricao_alimentar="Alergia a corantes",
                horario_alimentacao_manha="09h",
                porcao_alimentacao_manha="50g",
                horario_alimentacao_tarde="14h",
                porcao_alimentacao_tarde="30g",
                horario_alimentacao_noite="20h",
                porcao_alimentacao_noite="50g",
                restricao_medica=False,
                utiliza_medicacao=False,
                comportamento="Late bastante para estranhos, mas é um doce com quem conhece. Colo o tempo todo.",
                medo="Pessoas com chapéu ou guarda-chuva.",
                relacionamento_com_outros_animais="Tem medo de cachorros grandes, prefere ficar longe.",
                relacionamento_com_pessoas="Desconfiado no início.",
                dependente=True,
                experiencia_com_hospedagem=True,
                descricao_experiencia_com_hospedagem="Fica na casa da avó quando a tutora viaja.",
                posse_alimento=False,
                posse_objeto=True,
                descricao_posse_objeto="Tem ciúmes do ursinho de pelúcia azul."
            ),

            Cachorro(
                nome="Bruce",
                raca="Bulldog Francês",
                data_nascimento=date(2021, 6, 12),
                porte="Pequeno",
                nome_tutor="Carlos Mendes",
                contato="41966665555",
                endereco_tutor="Av. República Argentina, 1500",
                castrado=True,
                vacina_antirrabica=date(2025, 9, 5),
                vacina_polivalente=date(2026, 1, 20),
                necessidades_em_casa=True,
                plano_de_saude=False,
                passeia=False,
                contato_veterinario="4132323232",
                endereco_clinica_veterinaria="Av. Silva Jardim, 400",
                restricao_alimentar=True,
                descricao_restricao_alimentar="Ração hipoalergênica apenas",
                horario_alimentacao_manha="08h",
                porcao_alimentacao_manha="100g",
                horario_alimentacao_noite="19h",
                porcao_alimentacao_noite="100g",
                restricao_medica=True,
                descricao_restricao_medica="Dermatite atópica e respiração ofegante em dias quentes. Evitar sol forte.",
                utiliza_medicacao=True,
                descricao_utiliza_medicacao="Apoquel uso contínuo se tiver crise de coceira.",
                comportamento="Preguiçoso e teimoso. Dorme a maior parte do dia.",
                relacionamento_com_outros_animais="Indiferente, não gosta muito de interagir.",
                relacionamento_com_pessoas="Gosta de carinho mas não é grudento.",
                dependente=False,
                experiencia_com_hospedagem=False,
                posse_alimento=False,
                posse_objeto=False,
            ),

            Cachorro(
                nome="Luna",
                raca="Border Collie",
                data_nascimento=date(2023, 1, 15),
                porte="Médio",
                nome_tutor="Juliana Lima",
                contato="41955554444",
                contato_2="41888880000",
                endereco_tutor="Rua Nilo Peçanha, 200",
                castrado=True,
                vacina_antirrabica=date(2026, 1, 10),
                vacina_polivalente=date(2026, 1, 10),
                necessidades_em_casa=False,
                plano_de_saude=True,
                nome_plano_de_saude="Petlove",
                passeia=True,
                contato_veterinario="41988881111",
                endereco_clinica_veterinaria="Rua Mateus Leme, 1200",
                restricao_alimentar=False,
                horario_alimentacao_manha="07h",
                porcao_alimentacao_manha="180g",
                horario_alimentacao_tarde="13h",
                porcao_alimentacao_tarde="50g (treino)",
                horario_alimentacao_noite="20h",
                porcao_alimentacao_noite="150g",
                restricao_medica=False,
                utiliza_medicacao=False,
                comportamento="Energia infinita. Precisa de enriquecimento ambiental ou destrói coisas.",
                medo="Sons de moto.",
                relacionamento_com_outros_animais="Tenta pastorear outros cachorros.",
                relacionamento_com_pessoas="Muito sociável.",
                dependente=True,
                experiencia_com_hospedagem=True,
                descricao_experiencia_com_hospedagem="Vai para day care todo dia.",
                posse_alimento=False,
                posse_objeto=True,
                descricao_posse_objeto="Bolinhas de tênis. Não tente tirar da boca dela sem oferecer troca."
            ),

            Cachorro(
                nome="Simba",
                raca="Spitz Alemão",
                data_nascimento=date(2021, 12, 25),
                porte="Pequeno",
                nome_tutor="Roberto Gomes",
                contato="41944443333",
                contato_2="41987654321",
                endereco_tutor="Av. Batel, 100",
                castrado=False,
                vacina_antirrabica=date(2025, 8, 20),
                vacina_polivalente=date(2025, 8, 20),
                necessidades_em_casa=True,
                plano_de_saude=False,
                passeia=True,
                contato_veterinario="4130303030",
                endereco_clinica_veterinaria="Rua Gonçalves Dias, 50",
                restricao_alimentar=False,
                horario_alimentacao_manha="08h",
                porcao_alimentacao_manha="60g",
                horario_alimentacao_noite="19h",
                porcao_alimentacao_noite="60g",
                restricao_medica=False,
                utiliza_medicacao=False,
                comportamento="Late para alertar qualquer movimento. Muito inteligente.",
                medo="Secador de cabelo.",
                relacionamento_com_outros_animais="Se acha grande, enfrenta cachorros maiores.",
                relacionamento_com_pessoas="Escolhe de quem gosta. Ignora quem não conhece.",
                dependente=False,
                experiencia_com_hospedagem=False,
                posse_alimento=False,
                posse_objeto=False,
            ),

            Cachorro(
                nome="Bob",
                raca="Labrador",
                data_nascimento=date(2018, 4, 10),
                porte="Grande",
                nome_tutor="Eduardo Silva",
                contato="41933332222",
                contato_2="41333555777",
                endereco_tutor="Rua Fagundes Varela, 500",
                castrado=True,
                vacina_antirrabica=date(2025, 5, 30),
                vacina_polivalente=date(2025, 6, 15),
                necessidades_em_casa=False,
                plano_de_saude=True,
                nome_plano_de_saude="Porto Pet",
                passeia=True,
                contato_veterinario="41991112222",
                endereco_clinica_veterinaria="Av. Nossa Senhora da Luz, 800",
                restricao_alimentar=False,
                horario_alimentacao_manha="07h",
                porcao_alimentacao_manha="250g",
                horario_alimentacao_noite="18h",
                porcao_alimentacao_noite="250g",
                restricao_medica=True,
                descricao_restricao_medica="Displasia leve no quadril. Evitar pisos muito lisos.",
                utiliza_medicacao=False,
                comportamento="Comilão e extremamente dócil. Balança o rabo derrubando coisas.",
                relacionamento_com_outros_animais="Brinca com todos.",
                relacionamento_com_pessoas="Ama todos, pula para lamber.",
                dependente=False,
                experiencia_com_hospedagem=True,
                descricao_experiencia_com_hospedagem="Já ficou em hotelzinho várias vezes.",
                posse_alimento=True,
                posse_objeto=False,
            ),

            Cachorro(
                nome="Nina",
                raca="Shih Tzu",
                data_nascimento=date(2024, 2, 14),
                porte="Pequeno",
                nome_tutor="Camila Rocha",
                contato="41922221111",
                contato_2="41888822222",
                endereco_tutor="Rua Brigadeiro Franco, 2300",
                castrado=False,
                vacina_antirrabica=date(2025, 7, 1),
                vacina_polivalente=date(2025, 7, 1),
                necessidades_em_casa=True,
                plano_de_saude=False,
                passeia=True,
                contato_veterinario="4133221100",
                endereco_clinica_veterinaria="Rua Desembargador Motta, 1500",
                restricao_alimentar=False,
                horario_alimentacao_manha="08h30",
                porcao_alimentacao_manha="70g",
                horario_alimentacao_noite="19h30",
                porcao_alimentacao_noite="70g",
                restricao_medica=False,
                utiliza_medicacao=False,
                comportamento="Calma, gosta de colo e de ficar no sofá.",
                medo="Aspirador de pó.",
                relacionamento_com_outros_animais="Tranquila.",
                relacionamento_com_pessoas="Dócil.",
                dependente=True,
                experiencia_com_hospedagem=False,
                posse_alimento=False,
                posse_objeto=False,
            ),

            Cachorro(
                nome="Zeus",
                raca="Rottweiler",
                data_nascimento=date(2019, 11, 20),
                porte="Grande",
                nome_tutor="Ricardo Almeida",
                contato="41911110000",
                endereco_tutor="Rua Holanda, 300",
                castrado=True,
                vacina_antirrabica=date(2025, 11, 20),
                vacina_polivalente=date(2025, 11, 20),
                necessidades_em_casa=False,
                plano_de_saude=False,
                passeia=True,
                contato_veterinario="4135556666",
                endereco_clinica_veterinaria="Av. Anita Garibaldi, 900",
                restricao_alimentar=False,
                horario_alimentacao_manha="06h",
                porcao_alimentacao_manha="300g",
                horario_alimentacao_noite="18h",
                porcao_alimentacao_noite="300g",
                restricao_medica=False,
                utiliza_medicacao=False,
                comportamento="Guardião da casa, mas um bebê com a família. Não gosta de movimentos bruscos.",
                relacionamento_com_outros_animais="Dominante. Precisa de aproximação lenta.",
                relacionamento_com_pessoas="Indiferente com estranhos na rua, protetor em casa.",
                dependente=False,
                experiencia_com_hospedagem=False,
                posse_alimento=True,
                posse_objeto=False,
            ),

            Cachorro(
                nome="Lola",
                raca="Beagle",
                data_nascimento=date(2020, 10, 5),
                porte="Médio",
                nome_tutor="Patricia Santos",
                contato="41900009999",
                contato_2="41132435467",
                endereco_tutor="Rua Itupava, 600",
                castrado=True,
                vacina_antirrabica=date(2025, 9, 15),
                vacina_polivalente=date(2025, 9, 15),
                necessidades_em_casa=False,
                plano_de_saude=True,
                nome_plano_de_saude="Petlove",
                passeia=True,
                contato_veterinario="4134445555",
                endereco_clinica_veterinaria="Rua Alberto Bolliger, 100",
                restricao_alimentar=False,
                horario_alimentacao_manha="08h",
                porcao_alimentacao_manha="130g",
                horario_alimentacao_noite="19h",
                porcao_alimentacao_noite="130g",
                restricao_medica=True,
                descricao_restricao_medica="Tendência a obesidade, controlar petiscos.",
                utiliza_medicacao=False,
                comportamento="Farejadora, teimosa e muito vocal. Uiva quando sozinha.",
                medo="Ficar sozinha.",
                relacionamento_com_outros_animais="Brincalhona, gosta de matilha.",
                relacionamento_com_pessoas="Adora crianças.",
                dependente=True,
                experiencia_com_hospedagem=True,
                descricao_experiencia_com_hospedagem="Fica bem em hospedagem se tiver companhia.",
                posse_alimento=True,
                posse_objeto=False,
            )
        ]

        session.add_all(cachorros_demo)
        session.commit()

        print("Banco populado com dados de demonstração.")

if __name__ == "__main__":
    seed_database()